### ISSUE TITLE
A lot of visual problems

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [PrincessAkira/revolt-plus#1]
bottom is raised for some reason,
![image](https://user-images.githubusercontent.com/76877633/144937897-4d3f2165-c5f1-454f-94a5-e4c0803e6b02.png)
 top bar is lower than the server/channel list,
![image](https://user-images.githubusercontent.com/76877633/144937938-08b0f624-dbf9-4b8f-8e4c-6ac37925ba88.png)
 replies are normal,
![image](https://user-images.githubusercontent.com/76877633/144937958-5e3396a8-0af0-466c-9a51-f2c808676174.png)
 server selection icon looks out of place,
![image](https://user-images.githubusercontent.com/76877633/144937977-f06182fc-6f74-477d-a20b-2eaba9cc717f.png)
 editing messages is normal,
![image](https://user-images.githubusercontent.com/76877633/144937999-0dc12b4f-bd4e-4caf-8167-c02f04c98f47.png)
 abrupt cutoff at top of message field,
![image](https://user-images.githubusercontent.com/76877633/144938017-09188a2f-67d1-44f2-988c-9ac85ba800b0.png)
 connecting message looks out of place,
![image](https://user-images.githubusercontent.com/76877633/144938076-f27ff75e-e380-44e1-b958-50bdb0c1181c.png)
 cant really see which channel is selected,
![image](https://user-images.githubusercontent.com/76877633/144938104-b928aea2-5834-4388-8c82-69448aefa668.png)
 profiles are still default colors,
![image](https://user-images.githubusercontent.com/76877633/144938131-46a36125-3090-493f-bb51-9af4d18aa6e6.png)
 channel selector scrollbar goes off of its track,
![image](https://user-images.githubusercontent.com/76877633/144937856-8536eaaf-87bd-44ef-bf9e-3f4c53e952bd.png)
 inconsistent spacing between the message and channel fields and the message and member fields,
![image](https://user-images.githubusercontent.com/76877633/144937792-a0754711-348c-4ae9-9053-857ddb489933.png)
 message box looks broken of there's no image perms,
![image](https://user-images.githubusercontent.com/76877633/144938258-61f17af6-c0c9-44d9-9f16-55876543240c.png)
top bar is further away from channel list than messages,
![image](https://user-images.githubusercontent.com/76877633/144938327-90b68933-db8f-4383-95ca-36df3c46ff7c.png)
settings isnt themed at all,
![image](https://user-images.githubusercontent.com/76877633/144938426-fdaba521-3db2-4acc-ab39-76a227d61917.png)
messages from the same user arnt joined in the same message box,
![image](https://user-images.githubusercontent.com/76877633/144938512-ee3bce31-62e6-43c8-b4df-dadeee14c3cc.png)
cutoff at the top of member list,
![image](https://user-images.githubusercontent.com/76877633/144938620-805a811e-2a9c-4276-ba99-e2a6dc4a93ca.png)
pfp isnt centered in message field,
![image](https://user-images.githubusercontent.com/76877633/144938764-fc286ff6-19e0-40a7-adb0-6efdace4d27a.png)
dates in chat dont have rounded edges,
![image](https://user-images.githubusercontent.com/76877633/144938803-dda8fd74-2831-480b-ad84-2f8c843d5649.png)
\* is typing isnt themed,
![image](https://user-images.githubusercontent.com/76877633/144938886-b5dabdc1-6d8e-4d6b-8b7f-c2fdcdf8d055.png)
context menus ant themed,
![image](https://user-images.githubusercontent.com/76877633/144939057-0deff502-a259-45a1-9ab9-aeb97137a2fd.png)
this thing in search menu with owo language,
![image](https://user-images.githubusercontent.com/76877633/144939131-bb31d501-f451-4152-9c94-cb34cdabe1ea.png)
awkward gap between messages and input,
![image](https://user-images.githubusercontent.com/76877633/144939207-243ea758-a03e-4cd5-97bc-c65411eac942.png)

**Comment by HerXayah** [comment]
ughhhhh

**Comment by NULLYUKI** [comment]
> ughhhhh

@PrincessAkira Please fix all the mentioned issues and update it for the latest Revolt version.

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
Damn, this issue is getting attention after 1 and a half years.

**Comment by NULLYUKI** [comment]
Theme is discontinued.
https://github.com/PrincessAkira/revolt-plus/issues/2#issuecomment-1720060029
