### ISSUE TITLE
Update the Theme

### ISSUE THREAD

**Issue by NULLYUKI** [PrincessAkira/revolt-plus#2]
As Revolt has now received many different updates, I think a whole new update of the theme would be appreciated and to fix the issues that were found in #1

**Comment by NULLYUKI** [comment]
@PrincessAkira

**Comment by NULLYUKI** [comment]
@PrincessAkira Will this theme ever be updated to work with the latest Revolt version?

**Comment by HerXayah** [comment]
nope

**Comment by NULLYUKI** [comment]
> nope

Then archive this project or so lol
Also still waiting for the reason.
